// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

const _sweetlineAssetId = 'package:sweetline/lib/sweetline.dart';

/// Create a managed document (Document)
/// @param uri Document URI
/// @param text Document content
/// @return Managed document handle
@ffi.Native<
  sl_document_handle_t Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
>(assetId: _sweetlineAssetId)
external sl_document_handle_t sl_create_document(
  ffi.Pointer<ffi.Char> uri,
  ffi.Pointer<ffi.Char> text,
);

/// Destroy a managed document
/// @param document_handle Managed document handle
/// @return Error code, see @see {sl_error_t}. Returns @see {SL_OK} on success
@ffi.Native<ffi.Int Function(sl_document_handle_t)>(assetId: _sweetlineAssetId, symbol: 'sl_free_document')
external int _sl_free_document(sl_document_handle_t document_handle);

sl_error sl_free_document(sl_document_handle_t document_handle) =>
    sl_error.fromValue(_sl_free_document(document_handle));

/// Create a SweetLine highlight engine
/// @param show_index Whether the analysis result includes character index, if not only line and column are returned
/// @param inline_style Whether the analysis result uses inline styles instead of only returning style IDs
/// @return Highlight engine handle
@ffi.Native<sl_engine_handle_t Function(ffi.Bool, ffi.Bool)>(assetId: _sweetlineAssetId)
external sl_engine_handle_t sl_create_engine(
  bool show_index,
  bool inline_style,
);

/// Destroy the highlight engine
/// @param engine_handle Highlight engine handle
/// @return Error code, returns @see {SL_OK} on success
@ffi.Native<ffi.Int Function(sl_engine_handle_t)>(assetId: _sweetlineAssetId, symbol: 'sl_free_engine')
external int _sl_free_engine(sl_engine_handle_t engine_handle);

sl_error sl_free_engine(sl_engine_handle_t engine_handle) =>
    sl_error.fromValue(_sl_free_engine(engine_handle));

/// Define a macro for controlling #ifdef conditional compilation in importSyntax
/// @param engine_handle Highlight engine handle
/// @param macro_name Macro name
/// @return Error code, returns @see {SL_OK} on success
@ffi.Native<ffi.Int Function(sl_engine_handle_t, ffi.Pointer<ffi.Char>)>(assetId: _sweetlineAssetId,
  symbol: 'sl_engine_define_macro',
)
external int _sl_engine_define_macro(
  sl_engine_handle_t engine_handle,
  ffi.Pointer<ffi.Char> macro_name,
);

sl_error sl_engine_define_macro(
  sl_engine_handle_t engine_handle,
  ffi.Pointer<ffi.Char> macro_name,
) => sl_error.fromValue(_sl_engine_define_macro(engine_handle, macro_name));

/// Undefine a macro
/// @param engine_handle Highlight engine handle
/// @param macro_name Macro name
/// @return Error code, returns @see {SL_OK} on success
@ffi.Native<ffi.Int Function(sl_engine_handle_t, ffi.Pointer<ffi.Char>)>(assetId: _sweetlineAssetId,
  symbol: 'sl_engine_undefine_macro',
)
external int _sl_engine_undefine_macro(
  sl_engine_handle_t engine_handle,
  ffi.Pointer<ffi.Char> macro_name,
);

sl_error sl_engine_undefine_macro(
  sl_engine_handle_t engine_handle,
  ffi.Pointer<ffi.Char> macro_name,
) => sl_error.fromValue(_sl_engine_undefine_macro(engine_handle, macro_name));

/// Compile syntax rules (directly from JSON content)
/// @param engine_handle Highlight engine handle
/// @param syntax_json Syntax rule JSON configuration
/// @return Syntax rule error information (if any)
@ffi.Native<
  sl_syntax_error_t Function(sl_engine_handle_t, ffi.Pointer<ffi.Char>)
>(assetId: _sweetlineAssetId)
external sl_syntax_error_t sl_engine_compile_json(
  sl_engine_handle_t engine_handle,
  ffi.Pointer<ffi.Char> syntax_json,
);

/// Compile syntax rules (from a JSON configuration file)
/// @param engine_handle Highlight engine handle
/// @param syntax_file Path to the syntax rule JSON file
/// @return Syntax rule error information (if any)
@ffi.Native<
  sl_syntax_error_t Function(sl_engine_handle_t, ffi.Pointer<ffi.Char>)
>(assetId: _sweetlineAssetId)
external sl_syntax_error_t sl_engine_compile_file(
  sl_engine_handle_t engine_handle,
  ffi.Pointer<ffi.Char> syntax_file,
);

/// Register a style name mapping from style name to ID
/// @param engine_handle Highlight engine handle
/// @param style_name Highlight style name
/// @param style_id Highlight style ID
/// @return Error code, returns @see {SL_OK} on success
@ffi.Native<
  ffi.Int Function(sl_engine_handle_t, ffi.Pointer<ffi.Char>, ffi.Int32)
>(assetId: _sweetlineAssetId, symbol: 'sl_engine_register_style_name')
external int _sl_engine_register_style_name(
  sl_engine_handle_t engine_handle,
  ffi.Pointer<ffi.Char> style_name,
  int style_id,
);

sl_error sl_engine_register_style_name(
  sl_engine_handle_t engine_handle,
  ffi.Pointer<ffi.Char> style_name,
  int style_id,
) => sl_error.fromValue(
  _sl_engine_register_style_name(engine_handle, style_name, style_id),
);

/// Get style name by style ID
/// @param engine_handle Highlight engine handle
/// @param style_id Highlight style ID
/// @return The registered style name for the given ID in the engine
@ffi.Native<ffi.Pointer<ffi.Char> Function(sl_engine_handle_t, ffi.Int32)>(assetId: _sweetlineAssetId)
external ffi.Pointer<ffi.Char> sl_engine_get_style_name(
  sl_engine_handle_t engine_handle,
  int style_id,
);

/// Create a plain text highlight analyzer by syntax rule name (no incremental analysis support)
/// @param engine_handle Highlight engine handle
/// @param syntax_name Syntax rule name
/// @return Plain text highlight analyzer handle
@ffi.Native<
  sl_analyzer_handle_t Function(sl_engine_handle_t, ffi.Pointer<ffi.Char>)
>(assetId: _sweetlineAssetId)
external sl_analyzer_handle_t sl_engine_create_text_analyzer(
  sl_engine_handle_t engine_handle,
  ffi.Pointer<ffi.Char> syntax_name,
);

/// Create a plain text highlight analyzer by file name (no incremental analysis support)
/// @param engine_handle Highlight engine handle
/// @param file_name File name or basename used for syntax routing
/// @return Plain text highlight analyzer handle
@ffi.Native<
  sl_analyzer_handle_t Function(sl_engine_handle_t, ffi.Pointer<ffi.Char>)
>(assetId: _sweetlineAssetId)
external sl_analyzer_handle_t sl_engine_create_text_analyzer_by_file_name(
  sl_engine_handle_t engine_handle,
  ffi.Pointer<ffi.Char> file_name,
);

/// Perform full highlight analysis on a text
/// @param analyzer_handle Plain text highlight analyzer handle
/// @param text Full text content
/// @return Analysis result, tightly packed in byte order. Structure:
/// @code
/// result[0] = span payload flags
/// bit0: hasStartIndex
/// bit1: inlineStyle
/// result[1] = span field count (stride)
/// result[2] = line count
/// Followed by line_count line entries:
/// line_entry[0] = span count of current line
/// Followed by span_count * stride fields
/// Span payload:
/// common: [column, length]
/// if show_index=true: append [startIndex]
/// if inline_style=true: append [foregroundColor, backgroundColor, fontAttributes]
/// else: append [styleId]
/// fontAttributes bitmask:
/// (bits & 1) != 0 => bold
/// (bits & (1 << 1)) != 0 => italic
/// (bits & (1 << 2)) != 0 => strikethrough
/// @endcode
/// Note: the return value must be freed by calling sl_free_buffer after use
@ffi.Native<
  ffi.Pointer<ffi.Int32> Function(sl_analyzer_handle_t, ffi.Pointer<ffi.Char>)
>(assetId: _sweetlineAssetId)
external ffi.Pointer<ffi.Int32> sl_text_analyze(
  sl_analyzer_handle_t analyzer_handle,
  ffi.Pointer<ffi.Char> text,
);

/// Perform single line highlight analysis and return the result
/// @param analyzer_handle Plain text highlight analyzer handle
/// @param text Single line text content
/// @param line_info Metadata for the current line, must be an int32_t array of length 3:
/// @code
/// line_info[0] = current line number
/// line_info[1] = start highlight state, typically from the end_state of the previous line's result; line 0 starts at 0
/// line_info[2] = cumulative character count up to the current line, excluding line endings
/// @endcode
/// @return Analysis result, tightly packed in byte order. Structure:
/// @code
/// result[0] = span payload flags
/// bit0: hasStartIndex
/// bit1: inlineStyle
/// result[1] = number of integer fields per token span
/// result[2] = number of token spans
/// result[3] = state ID at the end of current line analysis
/// result[4] = total characters analyzed in current line (excluding line endings)
/// Followed by result[2] * result[1] integer fields (single-line span payload):
/// common: [column, length]
/// if show_index=true: append [startIndex]
/// if inline_style=true: append [foregroundColor, backgroundColor, fontAttributes]
/// else: append [styleId]
/// @endcode
/// Note: the return value must be freed by calling sl_free_buffer after use
@ffi.Native<
  ffi.Pointer<ffi.Int32> Function(
    sl_analyzer_handle_t,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Int32>,
  )
>(assetId: _sweetlineAssetId)
external ffi.Pointer<ffi.Int32> sl_text_analyze_line(
  sl_analyzer_handle_t analyzer_handle,
  ffi.Pointer<ffi.Char> text,
  ffi.Pointer<ffi.Int32> line_info,
);

/// Perform indent guide analysis on plain text (requires prior call to sl_text_analyze for highlight results)
/// @param analyzer_handle Plain text highlight analyzer handle
/// @param text Text content
/// @return Analysis result, format same as sl_document_analyze_indent_guides
/// Note: the return value must be freed by calling sl_free_buffer after use
@ffi.Native<
  ffi.Pointer<ffi.Int32> Function(sl_analyzer_handle_t, ffi.Pointer<ffi.Char>)
>(assetId: _sweetlineAssetId)
external ffi.Pointer<ffi.Int32> sl_text_analyze_indent_guides(
  sl_analyzer_handle_t analyzer_handle,
  ffi.Pointer<ffi.Char> text,
);

/// Load a managed document and get a document highlight analyzer handle (supports incremental analysis)
/// @param engine_handle Highlight engine handle
/// @param document_handle Managed document handle
/// @return Document highlight analyzer handle
@ffi.Native<
  sl_analyzer_handle_t Function(sl_engine_handle_t, sl_document_handle_t)
>(assetId: _sweetlineAssetId)
external sl_analyzer_handle_t sl_engine_load_document(
  sl_engine_handle_t engine_handle,
  sl_document_handle_t document_handle,
);

/// Perform full highlight analysis on a managed document (typically called once after initial document load)
/// @param analyzer_handle Document highlight analyzer handle
/// @return Analysis result, tightly packed in byte order. Structure:
/// @code
/// Same format as sl_text_analyze:
/// [flags, spanStride, lineCount, lineEntry...]
/// @endcode
/// Note: the return value must be freed by calling sl_free_buffer after use
@ffi.Native<ffi.Pointer<ffi.Int32> Function(sl_analyzer_handle_t)>(assetId: _sweetlineAssetId)
external ffi.Pointer<ffi.Int32> sl_document_analyze(
  sl_analyzer_handle_t analyzer_handle,
);

/// Perform highlight analysis on a managed document, returning only a highlight slice for the specified line range
/// @param analyzer_handle Document highlight analyzer handle
/// @param visible_range Visible line range, array structure: [startLine],[lineCount]
/// @return Highlight slice for the specified line range, tightly packed in byte order. Structure:
/// @code
/// Same format as sl_document_analyze_incremental_in_line_range:
/// [flags, spanStride, startLine, totalLineCount, lineCount, lineEntry...]
/// @endcode
/// Note: the return value must be freed by calling sl_free_buffer after use
@ffi.Native<
  ffi.Pointer<ffi.Int32> Function(sl_analyzer_handle_t, ffi.Pointer<ffi.Int32>)
>(assetId: _sweetlineAssetId)
external ffi.Pointer<ffi.Int32> sl_document_analyze_line_range(
  sl_analyzer_handle_t analyzer_handle,
  ffi.Pointer<ffi.Int32> visible_range,
);

/// Perform incremental highlight analysis on a managed document (called when document changes)
/// @param analyzer_handle Document highlight analyzer handle
/// @param changes_range Change range, array structure: [startLine],[startColumn],[endLine],[endColumn]
/// @param new_text Changed text
/// @return Full analysis result for the entire document, tightly packed in byte order. Structure:
/// @code
/// Same format as sl_text_analyze:
/// [flags, spanStride, lineCount, lineEntry...]
/// @endcode
/// Note: the return value must be freed by calling sl_free_buffer after use
@ffi.Native<
  ffi.Pointer<ffi.Int32> Function(
    sl_analyzer_handle_t,
    ffi.Pointer<ffi.Int32>,
    ffi.Pointer<ffi.Char>,
  )
>(assetId: _sweetlineAssetId)
external ffi.Pointer<ffi.Int32> sl_document_analyze_incremental(
  sl_analyzer_handle_t analyzer_handle,
  ffi.Pointer<ffi.Int32> changes_range,
  ffi.Pointer<ffi.Char> new_text,
);

/// Perform incremental highlight analysis on a managed document, returning only a highlight slice for the specified line range
/// @param analyzer_handle Document highlight analyzer handle
/// @param changes_range Change range, array structure: [startLine],[startColumn],[endLine],[endColumn]
/// @param new_text Changed text
/// @param visible_range Visible line range, array structure: [startLine],[lineCount]
/// @return Highlight slice for the specified line range, tightly packed in byte order. Structure:
/// @code
/// result[0] = span payload flags
/// bit0: hasStartIndex
/// bit1: inlineStyle
/// result[1] = span field count (stride)
/// result[2] = slice start line (start_line)
/// result[3] = total line count after patch (total_line_count)
/// result[4] = slice line count (line_count)
/// Followed by line_count line entries:
/// line_entry[0] = span count of current line
/// followed by span payloads (same span payload structure as sl_text_analyze)
/// @endcode
/// Note: the return value must be freed by calling sl_free_buffer after use
@ffi.Native<
  ffi.Pointer<ffi.Int32> Function(
    sl_analyzer_handle_t,
    ffi.Pointer<ffi.Int32>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Int32>,
  )
>(assetId: _sweetlineAssetId)
external ffi.Pointer<ffi.Int32> sl_document_analyze_incremental_in_line_range(
  sl_analyzer_handle_t analyzer_handle,
  ffi.Pointer<ffi.Int32> changes_range,
  ffi.Pointer<ffi.Char> new_text,
  ffi.Pointer<ffi.Int32> visible_range,
);

/// Get highlight slice from the current cached document highlight result
/// Requires prior call to sl_document_analyze or sl_document_analyze_incremental
/// @param analyzer_handle Document highlight analyzer handle
/// @param visible_range Visible line range, array structure: [startLine],[lineCount]
/// @return Highlight slice for the specified line range, tightly packed in byte order. Structure:
/// @code
/// Same format as sl_document_analyze_incremental_in_line_range:
/// [flags, spanStride, startLine, totalLineCount, lineCount, lineEntry...]
/// @endcode
/// Note: the return value must be freed by calling sl_free_buffer after use
@ffi.Native<
  ffi.Pointer<ffi.Int32> Function(sl_analyzer_handle_t, ffi.Pointer<ffi.Int32>)
>(assetId: _sweetlineAssetId)
external ffi.Pointer<ffi.Int32> sl_document_get_highlight_slice(
  sl_analyzer_handle_t analyzer_handle,
  ffi.Pointer<ffi.Int32> visible_range,
);

/// Perform indent guide analysis on a managed document (requires prior call to sl_document_analyze or sl_document_analyze_incremental)
/// @param analyzer_handle Document highlight analyzer handle
/// @return Analysis result, tightly packed in byte order. Structure:
/// @code
/// result[0] = number of indent guide lines (guide_count)
/// result[1] = fixed field count per guide line (stride=6)
/// result[2] = number of line states (line_count)
/// result[3] = field count per line state (4)
/// Followed by guide_count guide line entries, each with structure:
/// [column, start_line, end_line, nesting_level, scope_rule_id, branch_count, branch_line_0, branch_column_0, ...]
/// Note: actual length per guide line = stride + branch_count * 2
/// Followed by line_count line state entries, each with structure:
/// [nesting_level, scope_state, scope_column, indent_level]
/// where scope_state: 0=START, 1=END, 2=CONTENT
/// @endcode
/// Note: the return value must be freed by calling sl_free_buffer after use
@ffi.Native<ffi.Pointer<ffi.Int32> Function(sl_analyzer_handle_t)>(assetId: _sweetlineAssetId)
external ffi.Pointer<ffi.Int32> sl_document_analyze_indent_guides(
  sl_analyzer_handle_t analyzer_handle,
);

/// Free the memory of analysis results. All analysis functions returning int32_t*
/// (such as sl_text_analyze, sl_document_analyze, sl_document_analyze_incremental,
/// sl_document_analyze_incremental_in_line_range, sl_document_get_highlight_slice) must be freed via this function
/// @param result Highlight analysis result
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Int32>)>(assetId: _sweetlineAssetId)
external void sl_free_buffer(ffi.Pointer<ffi.Int32> result);

/// Error codes
enum sl_error {
  SL_OK(0),
  SL_HANDLE_INVALID(1),
  SL_JSON_PROPERTY_MISSED(-1),
  SL_JSON_PROPERTY_INVALID(-2),
  SL_PATTERN_INVALID(-3),
  SL_STATE_INVALID(-4),
  SL_JSON_INVALID(-5),
  SL_FILE_NOT_EXISTS(-6),
  SL_FILE_INVALID(-7),
  SL_IMPORT_SYNTAX_NOT_FOUND(-8),
  SL_STATE_REFERENCE_NOT_FOUND(-9),
  SL_INLINE_STYLE_REFERENCE_NOT_FOUND(-10);

  final int value;
  const sl_error(this.value);

  static sl_error fromValue(int value) => switch (value) {
    0 => SL_OK,
    1 => SL_HANDLE_INVALID,
    -1 => SL_JSON_PROPERTY_MISSED,
    -2 => SL_JSON_PROPERTY_INVALID,
    -3 => SL_PATTERN_INVALID,
    -4 => SL_STATE_INVALID,
    -5 => SL_JSON_INVALID,
    -6 => SL_FILE_NOT_EXISTS,
    -7 => SL_FILE_INVALID,
    -8 => SL_IMPORT_SYNTAX_NOT_FOUND,
    -9 => SL_STATE_REFERENCE_NOT_FOUND,
    -10 => SL_INLINE_STYLE_REFERENCE_NOT_FOUND,
    _ => throw ArgumentError('Unknown value for sl_error: $value'),
  };
}

/// Syntax rule error information
final class sl_syntax_error extends ffi.Struct {
  /// Error code
  @ffi.Int()
  external int err_codeAsInt;

  sl_error get err_code => sl_error.fromValue(err_codeAsInt);

  /// Error message
  external ffi.Pointer<ffi.Char> err_msg;
}

typedef sl_syntax_error_t = sl_syntax_error;

final class sl_document_handle extends ffi.Opaque {}

typedef sl_document_handle_t = ffi.Pointer<sl_document_handle>;

final class sl_engine_handle extends ffi.Opaque {}

typedef sl_engine_handle_t = ffi.Pointer<sl_engine_handle>;

final class sl_analyzer_handle extends ffi.Opaque {}

typedef sl_analyzer_handle_t = ffi.Pointer<sl_analyzer_handle>;
